In [61]:
import pandas as pd
import numpy as np

In [33]:
# Removing Duplicate Records : Tasks
#1. Identify duplicate rows.
#2. Count duplicate rows.
#3. Remove duplicates.
#4. Keep only the last occurrence.
df = pd.DataFrame({
"student_id": [101, 102, 103, 102, 104, 101],
"name": ["Abel", "Sara", "John", "Sara", "Helen", "Abel"],
"score": [80, 90, 75, 90, 88, 80]
})

In [4]:
print(df.duplicated())
print("\nduplicate count :", df.duplicated().sum())

0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool

duplicate count : 2

In [5]:
df_clean = df.drop_duplicates()
df_last = df.drop_duplicates(keep='last')
print (df_clean)
print (df_last)

   student_id   name  score
0         101   Abel     80
1         102   Sara     90
2         103   John     75
4         104  Helen     88
   student_id   name  score
2         103   John     75
3         102   Sara     90
4         104  Helen     88
5         101   Abel     80

In [10]:
#Duplicate Emails Tasks.
df = pd.DataFrame({
"id":[1,2,3,4],
"email":[
"a@gmail.com",
"b@gmail.com",
"a@gmail.com",
"c@gmail.com"
]
})

#1. Find duplicate emails
duplicates = df[df.duplicated(subset=["email"])]

print(duplicates)

   id        email
2   3  a@gmail.com

In [11]:
#2. Remove duplicate emails.
clean_df = df.drop_duplicates(subset=["email"])
print(clean_df)

   id        email
0   1  a@gmail.com
1   2  b@gmail.com
3   4  c@gmail.com

In [12]:
# Standardize City Names
df = pd.DataFrame({
"city":[
"addis ababa",
"ADDIS ABABA",
"Addis Ababa",
"adDis abAba"
]
})

In [16]:
#1. Convert to uppercase.
df["upper"] = df["city"].str.upper()

#2. Convert to lowercase.
df["lower"] = df["city"].str.lower()

#3. Convert to title case.
df["title"] = df["city"].str.title()

print(df)

          city        upper        lower        title
0  addis ababa  ADDIS ABABA  addis ababa  Addis Ababa
1  ADDIS ABABA  ADDIS ABABA  addis ababa  Addis Ababa
2  Addis Ababa  ADDIS ABABA  addis ababa  Addis Ababa
3  adDis abAba  ADDIS ABABA  addis ababa  Addis Ababa

In [20]:
# Remove Extra Spaces
df = pd.DataFrame({
"name":[
" Abel",
"Sara ",
" John ",
" Helen"
]
})

df["name"] = df["name"].str.strip()

print(df)

    name
0   Abel
1   Sara
2   John
3  Helen

In [59]:
# Standardize Dates
df = pd.DataFrame({
    "date":[
        "2026-01-05",
        "05/02/2026",
        "March 10, 2026",
        "2026.04.15"
    ]
})

#Tasks
#1. Convert to datetime.
#2. Standardize to YYYY-MM-DD.
#3. Extract year.
#4. Extract month.
    
df["date"] = pd.to_datetime(df["date"], format="mixed", dayfirst=False, errors="coerce")
df["formatted"] = df["date"].dt.strftime("%Y-%m-%d")
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month

print(df)

        date   formatted  year  month
0 2026-01-05  2026-01-05  2026      1
1 2026-05-02  2026-05-02  2026      5
2 2026-03-10  2026-03-10  2026      3
3 2026-04-15  2026-04-15  2026      4

In [31]:
#Kilograms to Pounds
df = pd.DataFrame({
"weight_kg":[55,70,85,100]
})

df["weight_lb"] = (df["weight_kg"] * 2.20462).round(2)
print(df)

   weight_kg  weight_lb
0         55     121.25
1         70     154.32
2         85     187.39
3        100     220.46

In [32]:
#Celsius to Fahrenheit
df = pd.DataFrame({
"temp_c":[0,25,37,100]
})
df["temp_f"] = (df["temp_c"] * 9/5) + 32

print(df)

   temp_c  temp_f
0       0    32.0
1      25    77.0
2      37    98.6
3     100   212.0

In [35]:
# Handling Missing Values
df = pd.DataFrame({
"name":["Abel","Sara",None,"John"],
"age":[20,np.nan,25,30]
})

In [39]:
#Find missing values.
df.isnull()

    name    age
0  False  False
1  False   True
2   True  False
3  False  False

In [38]:
df.isnull().sum()

name    1
age     1
dtype: int64

In [41]:
df["age"] = df["age"].fillna(df["age"].mean())
df["name"] = df["name"].fillna("Unknown")
df

      name   age
0     Abel  20.0
1     Sara  25.0
2  Unknown  25.0
3     John  30.0

In [43]:
#Correct Data Entry Errors
df = pd.DataFrame({
"gender":[
"Male",
"male",
"MALE",
"Female",
"female"
]
})

#Standardize gender values.
df["gender"] = df["gender"].str.title()

print(df)

   gender
0    Male
1    Male
2    Male
3  Female
4  Female

In [44]:
#Currency Conversion
df = pd.DataFrame({
"salary_usd":[500,800,1200,1500]
})

#Convert USD to ETB Assume 1 USD = 135 ETB.
exchange_rate = 135

df["salary_etb"] = df["salary_usd"] * exchange_rate

print(df)

   salary_usd  salary_etb
0         500       67500
1         800      108000
2        1200      162000
3        1500      202500

In [45]:
#Outlier Detection
df = pd.DataFrame({
"salary":[3500,4000,4200,3900,4100,45000]
})

Q1 = df["salary"].quantile(0.25)

Q3 = df["salary"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[
(df["salary"] < lower) |
(df["salary"] > upper)
]

print(outliers)

clean_df = df[
(df["salary"] >= lower) &
(df["salary"] <= upper)
]

print(clean_df)

   salary
0    3500
5   45000
   salary
1    4000
2    4200
3    3900
4    4100

In [46]:
# Phone Number Standardization

df = pd.DataFrame({
"phone":[
"0911223344",
"+251911223344",
"251911223344",
"0911-223-344"
]
})

#Remove symbols and Convert all numbers to +251 format.

df["phone"] = df["phone"].str.replace("-", "", regex=False)

df["phone"] = df["phone"].str.replace("+", "", regex=False)
df["phone"] = df["phone"].apply(
lambda x:
"+251" + x[1:]
if x.startswith("0")
else "+251" + x[3:]
)

print(df)

           phone
0  +251911223344
1  +251911223344
2  +251911223344
3  +251911223344

In [47]:
# Email Cleaning

df = pd.DataFrame({
"email":[
" ABEL@GMAIL.COM ",
"sara@gmail.com",
"JOHN@YAHOO.COM"
]
})

#1. Remove spaces.
#2. Convert to lowercase.
#3. Validate emails.

df["email"] = df["email"].str.strip()

df["email"] = df["email"].str.lower()

df["valid"] = df["email"].str.contains("@")

print(df)

            email  valid
0  abel@gmail.com   True
1  sara@gmail.com   True
2  john@yahoo.com   True

In [49]:
# Product Name Normalization
df = pd.DataFrame({
"product":[
"Laptop",
"laptop",
"LAPTOP",
"Laptop "
]
})

#unique counts before cleaning.
print("Before:", df["product"].nunique())

df["product"] = (
df["product"]
.str.strip()
.str.lower()
)

#unique counts after cleaning.
print("After:", df["product"].nunique())

Before: 4
After: 1

In [66]:
#Mixed Data Cleaning

df = pd.DataFrame({
"name":[" Abel ","Sara",None,"JOHN"],
"age":[20,np.nan,25,30],
"salary":[4000,4500,5000,45000],
"join_date":[
"2026-01-01",
"01/02/2026",
"March 10, 2026",
"2026.04.15"
]
})
df

     name   age  salary       join_date
0   Abel   20.0    4000      2026-01-01
1    Sara   NaN    4500      01/02/2026
2    None  25.0    5000  March 10, 2026
3    JOHN  30.0   45000      2026.04.15

In [68]:
#Tasks
#1. Clean names.
df['name'] =df['name'].fillna("UNKOWN")
#2. Fill missing values.
df['age'] =df['age'].fillna(df['age'].mean())

#3. Standardize dates.
df["join_date"] = pd.to_datetime(df["join_date"], format="mixed", dayfirst=False, errors="coerce")
df["DATE"] = df["join_date"].dt.strftime("%Y-%m-%d")

print (df)

#4. Detect outliers.
Q1 = df["salary"].quantile(0.25)
Q3 = df["salary"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
outliers = df[
(df["salary"] < lower) |
(df["salary"] > upper)
]
print("Outliers",outliers)

     name   age  salary  join_date        DATE
0   Abel   20.0    4000 2026-01-01  2026-01-01
1    Sara  25.0    4500 2026-01-02  2026-01-02
2  UNKOWN  25.0    5000 2026-03-10  2026-03-10
3    JOHN  30.0   45000 2026-04-15  2026-04-15
Outliers    name   age  salary  join_date        DATE
3  JOHN  30.0   45000 2026-04-15  2026-04-15