In [1]:
pip install pandas numpy

Requirement already satisfied: pandas in c:\users\isug\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\isug\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\isug\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\isug\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\isug\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\isug\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np

university= pd.DataFrame({
    "student_id" :[201,202,203,204,205,206,207,208,209,210],
    "name" : ["abel","sara",None,"john","marta",None,"david","helen","tom",None],
    "department" :["CS","IT","CS",None,"SE","IT","SE",None,"CS","IT"],
    "GPA": [3.5,3.8,np.nan ,2.9,3.7,np.nan , 3.2 ,3.4,3.9,np.nan],
    "scholarship": [5000 , np.nan, 3000 ,2000, np.nan,4000 , 3500,np.nan,5000,np.nan]
})

In [2]:
# whole table
university

   student_id   name department  GPA  scholarship
0         201   abel         CS  3.5       5000.0
1         202   sara         IT  3.8          NaN
2         203   None         CS  NaN       3000.0
3         204   john       None  2.9       2000.0
4         205  marta         SE  3.7          NaN
5         206   None         IT  NaN       4000.0
6         207  david         SE  3.2       3500.0
7         208  helen       None  3.4          NaN
8         209    tom         CS  3.9       5000.0
9         210   None         IT  NaN          NaN

In [8]:
# Data Cleaning Question No.1
print("--- Couting the missing values from each column ---")
print (university.isnull().sum())
print(f"the total number of missing values = {university.isnull().sum().sum()}")

--- Couting the missing values from each column ---
student_id     0
name           3
department     2
GPA            3
scholarship    4
dtype: int64
the total number of missing values = 12

In [10]:
# Data Cleaning Question No. 2
print("--- calculating the missing values percentage from each column ---")
(university.isnull().sum()/len(university))*100

--- calculating the missing values percentage from each column ---

student_id      0.0
name           30.0
department     20.0
GPA            30.0
scholarship    40.0
dtype: float64

In [15]:
# Data Cleaning Question No. 3
print("--- replace missing names by unknown  ---")
university['name']= university['name'].fillna("unknown")
print("--- university table after we replaced missing names by unknown ---")
university

--- replace missing names by unknown  ---
--- university table after we replaced missing names by unknown ---

   student_id     name department  GPA  scholarship
0         201     abel         CS  3.5       5000.0
1         202     sara         IT  3.8          NaN
2         203  unknown         CS  NaN       3000.0
3         204     john         IT  2.9       2000.0
4         205    marta         SE  3.7          NaN
5         206  unknown         IT  NaN       4000.0
6         207    david         SE  3.2       3500.0
7         208    helen         IT  3.4          NaN
8         209      tom         CS  3.9       5000.0
9         210  unknown         IT  NaN          NaN

In [16]:
# Data Cleaning Question No. 4
print("--- replace missing departments using mode  ---")
university['department']= university['department'].fillna(
    university['department'].mode()[0]
)
print("--- university table after we replaced missing departments by the common department ---")
university

--- replace missing departments using mode  ---
--- university table after we replaced missing departments by the common department ---

   student_id     name department  GPA  scholarship
0         201     abel         CS  3.5       5000.0
1         202     sara         IT  3.8          NaN
2         203  unknown         CS  NaN       3000.0
3         204     john         IT  2.9       2000.0
4         205    marta         SE  3.7          NaN
5         206  unknown         IT  NaN       4000.0
6         207    david         SE  3.2       3500.0
7         208    helen         IT  3.4          NaN
8         209      tom         CS  3.9       5000.0
9         210  unknown         IT  NaN          NaN

In [18]:
# Data Cleaning Question No. 5
print("--- replace missing gpa using median  ---")
university["GPA"] = university["GPA"].fillna(
university["GPA"].median()
)
print("--- university table after we replaced missing GPA by the Median of ther students GPA ---")
university

--- replace missing gpa using median  ---
--- university table after we replaced missing GPA by the Median of ther students GPA ---

   student_id     name department  GPA  scholarship
0         201     abel         CS  3.5       5000.0
1         202     sara         IT  3.8          NaN
2         203  unknown         CS  3.5       3000.0
3         204     john         IT  2.9       2000.0
4         205    marta         SE  3.7          NaN
5         206  unknown         IT  3.5       4000.0
6         207    david         SE  3.2       3500.0
7         208    helen         IT  3.4          NaN
8         209      tom         CS  3.9       5000.0
9         210  unknown         IT  3.5          NaN

In [19]:
# Data Cleaning Question No. 6
print("--- replace missing SCHOLARSHIPS with ZERO  ---")
university["scholarship"] = university["scholarship"].fillna(0)
print("--- university table after we replacedSCHOLARSHIPS with ZERO  ---")
university

--- replace missing SCHOLARSHIPS with ZERO  ---
--- university table after we replacedSCHOLARSHIPS with ZERO  ---

   student_id     name department  GPA  scholarship
0         201     abel         CS  3.5       5000.0
1         202     sara         IT  3.8          0.0
2         203  unknown         CS  3.5       3000.0
3         204     john         IT  2.9       2000.0
4         205    marta         SE  3.7          0.0
5         206  unknown         IT  3.5       4000.0
6         207    david         SE  3.2       3500.0
7         208    helen         IT  3.4          0.0
8         209      tom         CS  3.9       5000.0
9         210  unknown         IT  3.5          0.0

In [24]:
# Data Analysis Question No. 1
print("--- counting students by department  ---")
counts={}
for i , row in university.iterrows():
    deppartmentName = row['department']
    counts[deppartmentName] = counts.get(deppartmentName,0)+1
print(counts)

--- counting students by department  ---
{'CS': 3, 'IT': 5, 'SE': 2}

In [27]:
# Data Analysis Question No. 2
print("--- counting scholarship recipients ---")
for i, row in university.iterrows():
    if row['scholarship'] > 0.0:
        print(row["name"])

--- counting scholarship recipients ---
abel
unknown
john
unknown
david
tom

In [14]:
# Data Analysis Question No. 3
print("--- Finding the highest GPA ---")
highestGPA = university['GPA'].max()

# Find the student(s) with that GPA
studentsWithHighestGPA = university[university['GPA'] == highestGPA]

for index, row in studentsWithHighestGPA.iterrows():
    print(f"Name - {row['name']} \nGPA = {row['GPA']}")

--- Finding the highest GPA ---
Name - tom
GPA = 3.9

In [16]:
# Data Analysis Question No. 4
print("--- Finding the lowest GPA ---")
lowestGPA = university['GPA'].min()

# Find the student(s) with that GPA
studentsWithLowestGPA = university[university['GPA'] == lowestGPA]

for index, row in studentsWithLowestGPA.iterrows():
    print(f"Name - {row['name']} \nGPA = {row['GPA']}")

--- Finding the lowest GPA ---
Name - john
GPA = 2.9

In [18]:
# Data Analysis Question No. 5
print("--- average GPA ---")
print (f"mean = {university["GPA"].mean()}")

--- average GPA ---
mean = 3.4857142857142853

In [23]:
# Data Analysis Question No. 6
print("--- Sum of all Scholarships ---")
print (f"Total scholarships = {university["scholarship"].sum()}")

--- Sum of all Scholarships ---
Total scholarships = 22500.0