In [3]:
pip install pandas numpy

Requirement already satisfied: pandas in c:\users\isug\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy in c:\users\isug\anaconda3\lib\site-packages (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\isug\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\isug\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\isug\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\isug\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [45]:
import pandas as pd
import numpy as np

university= pd.DataFrame({
    "student_id" :[201,202,203,204,205,206,207,208,209,210],
    "name" : ["abel","sara",None,"john","marta",None,"david","helen","tom",None],
    "department" :["CS","IT","CS",None,"SE","IT","SE",None,"CS","IT"],
    "GPA": [3.5,3.8,np.nan ,2.9,3.7,np.nan , 3.2 ,3.4,3.9,np.nan],
    "scholarship": [5000 , np.nan, 3000 ,2000, np.nan,4000 , 3500,np.nan,5000,np.nan]
})

In [26]:
university

   student_id     name department  GPA  scholarship
0         201     abel         CS  3.5       5000.0
1         202     sara         IT  3.8          NaN
2         203  Unknown         CS  NaN       3000.0
3         204     john       None  2.9       2000.0
4         205    marta         SE  3.7          NaN
5         206  Unknown         IT  NaN       4000.0
6         207    david         SE  3.2       3500.0
7         208    helen       None  3.4          NaN
8         209      tom         CS  3.9       5000.0
9         210  Unknown         IT  NaN          NaN

In [14]:
university.isnull()
university.isnull().sum()

student_id     0
name           3
department     2
GPA            3
scholarship    4
dtype: int64

In [15]:
university.isnull().sum().sum()

np.int64(12)

In [16]:
# atleast one data is missing from the columns
university.isnull().any(axis=0)

student_id     False
name            True
department      True
GPA             True
scholarship     True
dtype: bool

In [ ]:
#replacing null string datas
fillna("")
#replacing null number datas
# option 1 - mean replace- replacing the data by the average of the available datas
# option 2 - mode replace - replacing by the highest frequented number
# option 3 - dropping by student.dropna()

In [19]:
(university.isnull().sum() / len(university)) * 100

student_id      0.0
name           30.0
department     20.0
GPA            30.0
scholarship    40.0
dtype: float64

In [21]:
university.columns[university.isnull().any()]

Index(['name', 'department', 'GPA', 'scholarship'], dtype='object')

In [22]:
university[university.isnull().any(axis=1)]

   student_id   name department  GPA  scholarship
1         202   sara         IT  3.8          NaN
2         203   None         CS  NaN       3000.0
3         204   john       None  2.9       2000.0
4         205  marta         SE  3.7          NaN
5         206   None         IT  NaN       4000.0
7         208  helen       None  3.4          NaN
9         210   None         IT  NaN          NaN

In [24]:
university[university["GPA"].isnull()]

   student_id  name department  GPA  scholarship
2         203  None         CS  NaN       3000.0
5         206  None         IT  NaN       4000.0
9         210  None         IT  NaN          NaN

In [33]:
university["name"] = university["name"].fillna("Unknown")
university

   student_id     name department  GPA  scholarship
0         201     abel         CS  3.5       5000.0
1         202     sara         IT  3.8          NaN
2         203  Unknown         CS  3.5       3000.0
3         204     john       None  2.9       2000.0
4         205    marta         SE  3.7          NaN
5         206  Unknown         IT  3.5       4000.0
6         207    david         SE  3.2       3500.0
7         208    helen       None  3.4          NaN
8         209      tom         CS  3.9       5000.0
9         210  Unknown         IT  3.5          NaN

In [30]:
university["GPA"] = university["GPA"].fillna(
university["GPA"].mean()
)
university

   student_id     name department       GPA  scholarship
0         201     abel         CS  3.500000       5000.0
1         202     sara         IT  3.800000          NaN
2         203  Unknown         CS  3.485714       3000.0
3         204     john       None  2.900000       2000.0
4         205    marta         SE  3.700000          NaN
5         206  Unknown         IT  3.485714       4000.0
6         207    david         SE  3.200000       3500.0
7         208    helen       None  3.400000          NaN
8         209      tom         CS  3.900000       5000.0
9         210  Unknown         IT  3.485714          NaN

In [34]:
university["GPA"] = university["GPA"].fillna(
university["GPA"].median()
)
university

   student_id     name department  GPA  scholarship
0         201     abel         CS  3.5       5000.0
1         202     sara         IT  3.8          NaN
2         203  Unknown         CS  3.5       3000.0
3         204     john       None  2.9       2000.0
4         205    marta         SE  3.7          NaN
5         206  Unknown         IT  3.5       4000.0
6         207    david         SE  3.2       3500.0
7         208    helen       None  3.4          NaN
8         209      tom         CS  3.9       5000.0
9         210  Unknown         IT  3.5          NaN

In [37]:
university["department"] = university["department"].fillna(
university["department"].mode()[0]
)
university

   student_id     name department  GPA  scholarship
0         201     abel         CS  3.5       5000.0
1         202     sara         IT  3.8          NaN
2         203  Unknown         CS  3.5       3000.0
3         204     john         CS  2.9       2000.0
4         205    marta         SE  3.7          NaN
5         206  Unknown         IT  3.5       4000.0
6         207    david         SE  3.2       3500.0
7         208    helen         CS  3.4          NaN
8         209      tom         CS  3.9       5000.0
9         210  Unknown         IT  3.5          NaN

In [38]:
university["scholarship"] = university["scholarship"].fillna(0)
university

   student_id     name department  GPA  scholarship
0         201     abel         CS  3.5       5000.0
1         202     sara         IT  3.8          0.0
2         203  Unknown         CS  3.5       3000.0
3         204     john         CS  2.9       2000.0
4         205    marta         SE  3.7          0.0
5         206  Unknown         IT  3.5       4000.0
6         207    david         SE  3.2       3500.0
7         208    helen         CS  3.4          0.0
8         209      tom         CS  3.9       5000.0
9         210  Unknown         IT  3.5          0.0

In [41]:
#Remove rows containing missing values.
university.dropna()

   student_id   name department  GPA  scholarship
0         201   abel         CS  3.5       5000.0
6         207  david         SE  3.2       3500.0
8         209    tom         CS  3.9       5000.0

In [44]:
#Remove columns containing missing values.
university.dropna(axis=1)

   student_id
0         201
1         202
2         203
3         204
4         205
5         206
6         207
7         208
8         209
9         210

In [47]:
#Create a GPA missing-value flag.
university["gpa_missing"] = university["GPA"].isnull()
university

   student_id   name department  GPA  scholarship  gpa_missing
0         201   abel         CS  3.5       5000.0        False
1         202   sara         IT  3.8          NaN        False
2         203   None         CS  NaN       3000.0         True
3         204   john       None  2.9       2000.0        False
4         205  marta         SE  3.7          NaN        False
5         206   None         IT  NaN       4000.0         True
6         207  david         SE  3.2       3500.0        False
7         208  helen       None  3.4          NaN        False
8         209    tom         CS  3.9       5000.0        False
9         210   None         IT  NaN          NaN         True

In [49]:
#Create a scholarship missing-value flag.
university["scholarship_missing"] = university["scholarship"].isnull()
university

,student_id,name,department,GPA,scholarship,gpa_missing,scholarship_missing
0,201,abel,CS,3.5,5000.0,False,False
1,202,sara,IT,3.8,NaN,False,True
2,203,None,CS,NaN,3000.0,True,False
3,204,john,None,2.9,2000.0,False,False
4,205,marta,SE,3.7,NaN,False,True
5,206,None,IT,NaN,4000.0,True,False
6,207,david,SE,3.2,3500.0,False,False
7,208,helen,None,3.4,NaN,False,True
8,209,tom,CS,3.9,5000.0,False,False
9,210,None,IT,NaN,NaN,True,True

In [52]:
#the column with the highest number of missing values.
print(f"max missing = {university.isnull().sum().idxmax()}")
print(f"minimum missing = {university.isnull().sum().idxmin()}")

max missing = scholarship
minimum missing = student_id

In [56]:
100 - (university.isnull().sum().sum() / university.size) *100

np.float64(82.85714285714286)