In [2]:
import pandas as pd

In [3]:
print(pd.__version__)

2.3.3

In [15]:
# Series = one dimensional labeled array/single column that can contain any datatype

In [13]:
# example 1
data=[100,101,102,103]
series = pd.Series(data)
series

0    100
1    101
2    102
3    103
dtype: int64

In [8]:
print(series.loc[1])

101

In [9]:
print(series[series>=102])

2    102
3    103
dtype: int64

In [11]:
#example 2 using dictionaries
calories= {'day1':1750 ,'day2':2100 ,'day3':1700 }
series =pd.Series(calories)
series

day1    1750
day2    2100
day3    1700
dtype: int64

In [14]:
# excersise 1
data=['bulbasaur','lvysaur','venusaur','charmander','charmeleon','charizard']
series = pd.Series(data,index=[1,2,3,4,5,6])
series

1     bulbasaur
2       lvysaur
3      venusaur
4    charmander
5    charmeleon
6     charizard
dtype: object

In [ ]:
# dataframe : 2 dimentional tabular data structure with rows and columns

In [16]:
data = {
    'name':['abebe','kebede','chala'],
    'age' : [30,35,59]
       }
df =pd.DataFrame(data)
df

     name  age
0   abebe   30
1  kebede   35
2   chala   59

In [17]:
df =pd.DataFrame(data , index=[101,102,103])
df

       name  age
101   abebe   30
102  kebede   35
103   chala   59

In [18]:
# accesing a row using assigned index
print(df.loc[102])

name    kebede
age         35
Name: 102, dtype: object

In [20]:
# accesing a row using index number as an array
print(df.iloc[1])

name    kebede
age         35
Name: 102, dtype: object

In [23]:
# adding a new column
df['job'] =['artist','coder','N/A']
df

       name  age     job
101   abebe   30  artist
102  kebede   35   coder
103   chala   59     N/A

In [24]:
# adding a new ROW
newRow =pd.DataFrame([{ 'name':'hiwot' , 'age':'28' , 'job':'musician'}] , 
                    index=[104]
                    )
df=pd.concat([df,newRow])
df

       name age       job
101   abebe  30    artist
102  kebede  35     coder
103   chala  59       N/A
104   hiwot  28  musician

In [28]:
newRows =pd.DataFrame([{ 'name':'kal' , 'age':'34' , 'job':'engineer'},
                      { 'name':'john' , 'age':'38' , 'job':'developer'}
                      ] , 
                    index=[105,106]
                    )
df=pd.concat([df,newRows])
df

       name age        job
101   abebe  30     artist
102  kebede  35      coder
103   chala  59        N/A
104   hiwot  28   musician
105     kal  34   engineer
106    john  38  developer