In [29]:
import pandas as pd

In [42]:
# working with csv files
df=pd.read_csv('movies_updated.csv') # we can make the index one of the columns by index_col="name" syntax
df # make it df.to_string() to print all the rows and columns to not make i truncated

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,"runtime,,"
0,The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000,46998772.0,Warner Bros.,"146.0,"
1,The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000,58853106.0,Columbia Pictures,"104.0,"
2,Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000,538375067.0,Lucasfilm,"124.0,"
3,Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000,83453539.0,Paramount Pictures,"88.0,"
4,Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000,39846344.0,Orion Pictures,"98.0,"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,Birthday Girl,R,Comedy,2001,"February 1, 2002 (United States)",6.1,25000,Jez Butterworth,Tom Butterworth,Nicole Kidman,United Kingdom,13000000,16171098.0,FilmFour,"93.0,"
3996,Human Nature,R,Comedy,2001,"September 12, 2001 (France)",6.4,18000,Michel Gondry,Charlie Kaufman,Tim Robbins,France,0,1574660.0,Fine Line Features,"96.0,"
3997,Made,R,Comedy,2001,"August 31, 2001 (United States)",6.4,18000,Jon Favreau,Jon Favreau,Vince Vaughn,United States,5000000,5480653.0,Artisan Entertainment,"95.0,"
3998,One Night at McCool's,R,Comedy,2001,"April 27, 2001 (United States)",6.1,29000,Harald Zwart,Stan Seidel,Liv Tyler,United States,18000000,13578186.0,October Films,"93.0,"
3999,Dr. Dolittle 2,PG,Comedy,2001,"June 22, 2001 (United States)",4.7,42000,Steve Carr,Hugh Lofting,Eddie Murphy,United States,70000000,176104344.0,Twentieth Century Fox,"87.0,"

In [43]:
#fetching specific columns
print(df['name'])
print(df[['name','year']])

0                                          The Shining
1                                      The Blue Lagoon
2       Star Wars: Episode V - The Empire Strikes Back
3                                            Airplane!
4                                           Caddyshack
                             ...
3995                                     Birthday Girl
3996                                      Human Nature
3997                                              Made
3998                             One Night at McCool's
3999                                    Dr. Dolittle 2
Name: name, Length: 4000, dtype: object
                                                name  year
0                                        The Shining  1980
1                                    The Blue Lagoon  1980
2     Star Wars: Episode V - The Empire Strikes Back  1980
3                                          Airplane!  1980
4                                         Caddyshack  1980
...                                              ...   ...
3995                                   Birthday Girl  2001
3996                                    Human Nature  2001
3997                                            Made  2001
3998                           One Night at McCool's  2001
3999                                  Dr. Dolittle 2  2001

[4000 rows x 2 columns]

In [41]:
#fetching specific rows
print(df.loc[2])

name         Star Wars: Episode V - The Empire Strikes Back
rating                                                   PG
genre                                                Action
year                                                   1980
released                      June 20, 1980 (United States)
score                                                   8.7
votes                                               1200000
director                                     Irvin Kershner
writer                                       Leigh Brackett
star                                            Mark Hamill
country                                       United States
budget                                             18000000
gross                                           538375067.0
company                                           Lucasfilm
runtime,,                                            124.0,
Name: 2, dtype: object

In [47]:
df=pd.read_csv('movies_updated.csv',index_col="name" )
df

,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,"runtime,,"
name,,,,,,,,,,,,,,
The Shining,R,Drama,1980,"June 13, 1980 (United States)",8.4,927000,Stanley Kubrick,Stephen King,Jack Nicholson,United Kingdom,19000000,46998772.0,Warner Bros.,"146.0,"
The Blue Lagoon,R,Adventure,1980,"July 2, 1980 (United States)",5.8,65000,Randal Kleiser,Henry De Vere Stacpoole,Brooke Shields,United States,4500000,58853106.0,Columbia Pictures,"104.0,"
Star Wars: Episode V - The Empire Strikes Back,PG,Action,1980,"June 20, 1980 (United States)",8.7,1200000,Irvin Kershner,Leigh Brackett,Mark Hamill,United States,18000000,538375067.0,Lucasfilm,"124.0,"
Airplane!,PG,Comedy,1980,"July 2, 1980 (United States)",7.7,221000,Jim Abrahams,Jim Abrahams,Robert Hays,United States,3500000,83453539.0,Paramount Pictures,"88.0,"
Caddyshack,R,Comedy,1980,"July 25, 1980 (United States)",7.3,108000,Harold Ramis,Brian Doyle-Murray,Chevy Chase,United States,6000000,39846344.0,Orion Pictures,"98.0,"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Birthday Girl,R,Comedy,2001,"February 1, 2002 (United States)",6.1,25000,Jez Butterworth,Tom Butterworth,Nicole Kidman,United Kingdom,13000000,16171098.0,FilmFour,"93.0,"
Human Nature,R,Comedy,2001,"September 12, 2001 (France)",6.4,18000,Michel Gondry,Charlie Kaufman,Tim Robbins,France,0,1574660.0,Fine Line Features,"96.0,"
Made,R,Comedy,2001,"August 31, 2001 (United States)",6.4,18000,Jon Favreau,Jon Favreau,Vince Vaughn,United States,5000000,5480653.0,Artisan Entertainment,"95.0,"
One Night at McCool's,R,Comedy,2001,"April 27, 2001 (United States)",6.1,29000,Harald Zwart,Stan Seidel,Liv Tyler,United States,18000000,13578186.0,October Films,"93.0,"
Dr. Dolittle 2,PG,Comedy,2001,"June 22, 2001 (United States)",4.7,42000,Steve Carr,Hugh Lofting,Eddie Murphy,United States,70000000,176104344.0,Twentieth Century Fox,"87.0,"

In [48]:
print( df.loc['Dr. Dolittle 2']) # displayed by the name indexing

rating                                  PG
genre                               Comedy
year                                  2001
released     June 22, 2001 (United States)
score                                  4.7
votes                                42000
director                        Steve Carr
writer                        Hugh Lofting
star                          Eddie Murphy
country                      United States
budget                            70000000
gross                          176104344.0
company              Twentieth Century Fox
runtime,,                            87.0,
Name: Dr. Dolittle 2, dtype: object

In [50]:
print( df.loc['Dr. Dolittle 2' ,["year","budget"]]) # displayed by the name indexing and selecting specific columns to display

year          2001
budget    70000000
Name: Dr. Dolittle 2, dtype: object

In [53]:
print( df.loc['Birthday Girl':'Dr. Dolittle 2',["year","budget"]]) # displayed by the name indexing

                       year    budget
name
Birthday Girl          2001  13000000
Human Nature           2001         0
Made                   2001   5000000
One Night at McCool's  2001  18000000
Dr. Dolittle 2         2001  70000000

In [63]:
print( df.iloc[0:11 , 0:3]) # displayed by the indexing like an array

                                               rating      genre  year
name
The Shining                                         R      Drama  1980
The Blue Lagoon                                     R  Adventure  1980
Star Wars: Episode V - The Empire Strikes Back     PG     Action  1980
Airplane!                                          PG     Comedy  1980
Caddyshack                                          R     Comedy  1980
Friday the 13th                                     R     Horror  1980
The Blues Brothers                                  R     Action  1980
Raging Bull                                         R  Biography  1980
Superman II                                        PG     Action  1980
The Long Riders                                     R  Biography  1980
Any Which Way You Can                              PG     Action  1980

In [67]:
#SELECTION using pandas
movie =input ('enter the movie name')
try :
    print(df.loc[movie])
except KeyError:
    print(f'{movie} not found')

enter the movie name The Blue Lagoon

rating                                  R
genre                           Adventure
year                                 1980
released     July 2, 1980 (United States)
score                                 5.8
votes                               65000
director                   Randal Kleiser
writer            Henry De Vere Stacpoole
star                       Brooke Shields
country                     United States
budget                            4500000
gross                          58853106.0
company                 Columbia Pictures
runtime,,                          104.0,
Name: The Blue Lagoon, dtype: object

In [73]:
# Filtering by condition using pandas
recentMovies = df[df["year"]>2000]
print(recentMovies['genre'])

name
Harry Potter and the Sorcerer's Stone                Adventure
The Fast and the Furious                                Action
The Lord of the Rings: The Fellowship of the Ring       Action
Legally Blonde                                          Comedy
Mulholland Dr.                                           Drama
                                                       ...
Birthday Girl                                           Comedy
Human Nature                                            Comedy
Made                                                    Comedy
One Night at McCool's                                   Comedy
Dr. Dolittle 2                                          Comedy
Name: genre, Length: 157, dtype: object

In [91]:
#aggregation
print("Mean:")
print(df.mean(numeric_only = True)) # we can set all numeric value columns
print("\nsum score:")
print(df['score'].sum()) # we can set specific column
print("\nminimum score:")
print(df['score'].min())
print("\nmaximum vote:")
print(df['votes'].max())

Mean:
year      1.991191e+03
score     6.321950e+00
votes     5.449450e+04
budget    1.542740e+07
gross     4.172202e+07
dtype: float64

sum score:
25287.800000000003

minimum score:
2.2

maximum vote:
2400000