In [24]:
import pandas as pd
import numpy as np

In [9]:
#Dataset 1: Customers
customers = pd.DataFrame({
"Customer_ID": ["C001", "C002", "C003", "C004", "C005", "C006"],
"Customer_Name": ["Abel", "Sara", "John", "Helen", "Samuel",
"David"],
"City": ["Addis Ababa", "Adama", "Jimma", "Bahir Dar", "Hawassa",
"Dire Dawa"]
})
customers

  Customer_ID Customer_Name         City
0        C001          Abel  Addis Ababa
1        C002          Sara        Adama
2        C003          John        Jimma
3        C004         Helen    Bahir Dar
4        C005        Samuel      Hawassa
5        C006         David    Dire Dawa

In [10]:
#Dataset 2: Orders
orders = pd.DataFrame({
"Order_ID": [101,102,103,104,105,106,107],
"Customer_ID": ["C001","C002","C001","C004","C007","C006","C006"],
"Product":
["Laptop","Phone","Mouse","Keyboard","Tablet","Monitor","Printer"],
"Amount": [1200,800,45,150,650,700,300]
})
orders

   Order_ID Customer_ID   Product  Amount
0       101        C001    Laptop    1200
1       102        C002     Phone     800
2       103        C001     Mouse      45
3       104        C004  Keyboard     150
4       105        C007    Tablet     650
5       106        C006   Monitor     700
6       107        C006   Printer     300

In [11]:
#Exercise 1 — Customer Purchase Report
purchaseReport= pd.merge(
    customers,
    orders,
    on="Customer_ID",
    how = "inner"
)
purchaseReport

  Customer_ID Customer_Name         City  Order_ID   Product  Amount
0        C001          Abel  Addis Ababa       101    Laptop    1200
1        C001          Abel  Addis Ababa       103     Mouse      45
2        C002          Sara        Adama       102     Phone     800
3        C004         Helen    Bahir Dar       104  Keyboard     150
4        C006         David    Dire Dawa       106   Monitor     700
5        C006         David    Dire Dawa       107   Printer     300

In [ ]:
Questions
1. How many records are returned?
  - six
2. Which order is excluded from the report?
  - the fifth order
3. Why was that order excluded?
  - because Customer C007 is not registered

In [13]:
#Exercise 2 — Order Investigation
purchaseReport= pd.merge(
    customers,
    orders,
    how = "right"
)
purchaseReport

  Customer_ID Customer_Name         City  Order_ID   Product  Amount
0        C001          Abel  Addis Ababa       101    Laptop    1200
1        C002          Sara        Adama       102     Phone     800
2        C001          Abel  Addis Ababa       103     Mouse      45
3        C004         Helen    Bahir Dar       104  Keyboard     150
4        C007           NaN          NaN       105    Tablet     650
5        C006         David    Dire Dawa       106   Monitor     700
6        C006         David    Dire Dawa       107   Printer     300

In [ ]:
Questions
1. Which order has missing customer information?
  - order 105
2. Why is the customer information missing?
  - because Customer C007 is not registered
3. How many registered customers do not appear in this report?
  - two customer C003 and C005 didnt place any order

In [14]:
#Exercise 3 — Customer EngagementReport
purchaseReport= pd.merge(
    customers,
    orders,
    how = "left"
)
purchaseReport

  Customer_ID Customer_Name         City  Order_ID   Product  Amount
0        C001          Abel  Addis Ababa     101.0    Laptop  1200.0
1        C001          Abel  Addis Ababa     103.0     Mouse    45.0
2        C002          Sara        Adama     102.0     Phone   800.0
3        C003          John        Jimma       NaN       NaN     NaN
4        C004         Helen    Bahir Dar     104.0  Keyboard   150.0
5        C005        Samuel      Hawassa       NaN       NaN     NaN
6        C006         David    Dire Dawa     106.0   Monitor   700.0
7        C006         David    Dire Dawa     107.0   Printer   300.0

In [ ]:
Questions
1. Which customer has never placed an order?
  - C003 and C005 didnt place any order
2. What values appear for that customer's Product and Amount?
  - NaN
3. Why do those values appear?
  - b/c those customers didnt place any order and instead of empty data NaN values are placed

In [15]:
#Exercise 4 — Data Quality Audit
purchaseReport= pd.merge(
    customers,
    orders,
    how = "outer"
)
purchaseReport

  Customer_ID Customer_Name         City  Order_ID   Product  Amount
0        C001          Abel  Addis Ababa     101.0    Laptop  1200.0
1        C001          Abel  Addis Ababa     103.0     Mouse    45.0
2        C002          Sara        Adama     102.0     Phone   800.0
3        C003          John        Jimma       NaN       NaN     NaN
4        C004         Helen    Bahir Dar     104.0  Keyboard   150.0
5        C005        Samuel      Hawassa       NaN       NaN     NaN
6        C006         David    Dire Dawa     106.0   Monitor   700.0
7        C006         David    Dire Dawa     107.0   Printer   300.0
8        C007           NaN          NaN     105.0    Tablet   650.0

In [ ]:
Questions
1. How many rows are returned?
  - nine
2. Which registered customer has no orders?
  - customer C003 and C005
3. Which order belongs to a customer that is not registered?
   - order 105
4. Why are both records important to keep during a data quality audit?
  - it helps us to compare both customer and order table

In [26]:
# Exercise 5 — Customer Support Investigation
purchaseReport= pd.merge(
    customers,
    orders,
    how = "right"
)
print (purchaseReport[["Customer_Name" , "Product" , "Amount"]])

  Customer_Name   Product  Amount
0          Abel    Laptop    1200
1          Sara     Phone     800
2          Abel     Mouse      45
3         Helen  Keyboard     150
4           NaN    Tablet     650
5         David   Monitor     700
6         David   Printer     300

In [ ]:
Questions
1. How many orders has David placed?
  - two
2. What is his total spending?
  - 1000
3. Would this report include customers who have never placed orders? Explain your answer.
  - no because we are trying to search customers that had placed an order and whose name is david